#!/bin/bash

#Monitor memory when examining malware resource usage 
#This small program shows memory usage every x in seconds 
#
echo "Memory Status Information:"

echo "How often do you want updates? (1-10)"
read $freq

for i in {1..10}
do
 free -h 
 if [ "$freq" -le 10 ]; then 
  sleep $freq
 else
  sleep 10
 fi
done 
